# Generated by Django 4.0.4 on 2022-04-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_platform_alter_game_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
